# -*- coding: utf-8 -*-
"""linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c6zuRWvkWAjd1xCi9SX6Hmf-nVCwB_At
"""

import numpy as np
import sklearn
from sklearn import linear_model
height = [[4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0]]
weight = [8, 10, 12, 14, 16, 18, 20]
reg = linear_model.LinearRegression()
reg.fit(height, weight)
X_height = [[12.0]]
predicted_weight = reg.predict(X_height)
print(predicted_weight)

