# -*- coding: utf-8 -*-
"""ploynomialregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vBlF0264A2cwXbUEjBqSbhcsqLZHJMC
"""
#code
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures
x = [[4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0]]
y = [16, 25, 36, 49, 64, 81, 100]
lin_reg = LinearRegression()
lin_reg.fit(x, y)
print("Linear Regression Prediction for 11.0:", lin_reg.predict([[11.0]]))
polynomial_regression = make_pipeline(
    PolynomialFeatures(degree=1, include_bias=False),
    LinearRegression(),
)
polynomial_regression.fit(x, y)
X_height = [[20.0]]
target_predicted = polynomial_regression.predict(X_height)
print("Polynomial Regression Prediction for 20.0:", target_predicted)

